version: '3'

networks:
  observatory-dev:

services:
  database:
    image: 'postgres:9.4'
    env_file: .env.development
    networks:
      - observatory-dev
    ports:
      - 15432:5432

  redis:
    image: 'redis:3.0'
    env_file: .env.development
    networks:
      - observatory-dev
    ports:
      - 16379:6379
