version: '3'

networks:
  observatory-dev:
  observatory-test:

volumes:
  gorge-data:

services:
  database:
    image: 'lavode/observatory-database:9.4'
    env_file: .env.development
    networks:
      - observatory-dev
    ports:
      - 15432:5432

  database-test:
    image: 'lavode/observatory-database:9.4'
    env_file: .env.test
    networks:
      - observatory-test
    ports:
      - 25432:5432

  redis:
    image: 'redis:3.0'
    env_file: .env.development
    networks:
      - observatory-dev
    ports:
      - 16379:6379

  redis-test:
    image: 'redis:3.0'
    env_file: .env.test
    networks:
      - observatory-test
    ports:
      - 26379:6379

  gorge-database:
    image: 'postgres:9.6'
    env_file: .env.development.gorge
    networks:
      - observatory-dev

  gorge-redis:
    image: 'redis:3'
    env_file: .env.development.gorge
    networks:
      - observatory-dev

  gorge-application:
    image: 'lavode/gorge:0.1.0'
    env_file: .env.development.gorge
    command: application
    networks:
      - observatory-dev
    ports:
      - 8080:8080
    volumes:
      - gorge-data:/tmp/gorge
