version: '3'

networks:
  observatory-ci:

services:
  database-ci:
    image: 'lavode/observatory-database:9.4'
    env_file: .env.ci
    networks:
      - observatory-ci

  redis-ci:
    image: 'redis:3.0'
    env_file: .env.ci
    networks:
      - observatory-ci

  observatory-ci:
    build:
      context: .
      dockerfile: Dockerfile

    image: 'lavode/observatory:latest'
    env_file: .env.ci
    networks:
      - observatory-ci
    command: ci-spec
