---
update_stale_players:
  cron: '* * * * *'
  class: 'Observatory::StalePlayersUpdate'
  queue: stale_players_update
  args:
  description: 'Schedule update for all players with stale data'

clear_update_scheduled_at:
  cron: '* * * * *'
  class: 'Observatory::ClearUpdateScheduledAt'
  queue: clear_update_scheduled_at
  args:
  description: 'Clears `update scheduled at` flag after certain time passed'

delete_invalid_players:
  cron: '* * * * *'
  class: 'Observatory::DeleteInvalidPlayers'
  queue: delete_invalid_players
  args:
  description: 'Deletes players for whom no data could be retrieved'
